# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# .github/workflows/azure.yml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Free Trial (e234a7e4-58d4-46f2-83a0-058b8de16877)'
    backendAzureRmResourceGroupName: 'dev'
    backendAzureRmStorageAccountName: 'devlauren'
    backendAzureRmContainerName: 'devlauren'
    backendAzureRmKey: 'tf/terraform.tfstate'
